# Generated by Django 4.0.2 on 2022-02-01 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('customer_email', models.EmailField(max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, default='+', max_length=20, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Confirmed', 'Confirmed'), ('Canceled', 'Canceled'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('comment', models.TextField(blank=True, default='Please put here any comment', null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiddilycare.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100, null=True)),
                ('provider_email', models.EmailField(max_length=254, null=True)),
                ('provider_address', models.CharField(blank=True, max_length=200, null=True)),
                ('provider_phone', models.CharField(default='+', max_length=20, null=True)),
                ('provider_activty', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(default='Country', max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiddilycare.customer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiddilycare.order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('purchase_price', models.FloatField(null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('product_image', models.ImageField(default='Icon.png', null=True, upload_to='')),
                ('quantity', models.IntegerField(blank=True, default=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Clothes', 'Clothes'), ('Accessories', 'Accessories'), ('Electronic', 'Electronic')], max_length=100, null=True)),
                ('digital', models.BooleanField(default=False)),
                ('tax', models.FloatField(blank=True, default=0, null=True)),
                ('isPromotional', models.CharField(choices=[('Promo', 'Promo'), ('No Promo', 'No Promo')], default='No Promo', max_length=20)),
                ('promotion', models.FloatField(blank=True, default=0, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='')),
                ('provider', models.ForeignKey(blank=True, default='provider introuvable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiddilycare.provider')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kiddilycare.order')),
                ('product', models.ForeignKey(default='Product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiddilycare.product')),
            ],
        ),
    ]
