# Generated by Django 4.0.2 on 2022-03-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiddilycare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Beauté', 'Beaute'), ('Santé', 'Sante'), ('Accessoires', 'Accessoires'), ('Visage', 'Visage'), ('Corps', 'Corps'), ('PierresJade', 'PierresJade')], max_length=100, null=True),
        ),
    ]
