# Generated by Django 4.0.2 on 2022-03-18 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kiddilycare', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Beauté', 'Beaute'), ('Santé', 'Sante'), ('Accessoires', 'Accessoires'), ('Visage', 'Visage'), ('Corps', 'Corps'), ('Ete', 'Ete'), ('PierresJade', 'PierresJade')], max_length=100, null=True),
        ),
    ]
